from typing import Optional, List, Dict
from io import BytesIO
from datetime import datetime
from urllib.parse import urlparse
from collections import defaultdict
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration

from app.models.scan import Scan
from app.models.brand_profile import BrandProfile
from app.models.finding import Finding, FindingCategory, FindingSeverity


class PDFGenerator:
    """Generate consultant-grade PDF reports from scan data"""
    
    @staticmethod
    def generate_pdf(
        scan: Scan,
        brand_profile: Optional[BrandProfile] = None
    ) -> BytesIO:
        """Generate a PDF report for a scan"""
        
        html_content = PDFGenerator._build_html(scan, brand_profile)
        
        font_config = FontConfiguration()
        pdf_bytes = BytesIO()
        
        HTML(string=html_content).write_pdf(
            pdf_bytes,
            font_config=font_config
        )
        
        pdf_bytes.seek(0)
        return pdf_bytes
    
    @staticmethod
    def _build_html(scan: Scan, brand: Optional[BrandProfile] = None) -> str:
        """Build complete HTML document for PDF"""
        is_branded = brand is not None
        primary_color = brand.primary_color if brand else "#2563eb"
        accent_color = brand.accent_color if brand else "#10b981"
        brand_name = brand.name if brand else "SiteCheck"
        prepared_for = urlparse(scan.url).netloc if scan.url else "Client"
        
        # Get logo HTML
        logo_html = PDFGenerator._get_logo_html(brand)
        
        # Group and sort findings
        findings_by_category = PDFGenerator._group_findings(scan.findings)
        
        # Get quick wins
        quick_wins = PDFGenerator._get_quick_wins(scan.findings)
        
        # Get severity breakdown
        severity_counts = PDFGenerator._get_severity_counts(scan.findings)
        
        # Get redirect chain
        redirect_chain = PDFGenerator._parse_redirect_chain(scan.redirect_chain)
        
        # Build sections
        cover_page = PDFGenerator._build_cover_page(
            scan, brand, logo_html, primary_color, accent_color, brand_name, prepared_for
        )
        toc_page = PDFGenerator._build_toc_page()
        executive_summary = PDFGenerator._build_executive_summary(scan, severity_counts)
        score_breakdown = PDFGenerator._build_score_breakdown(scan, severity_counts, accent_color)
        findings_sections = PDFGenerator._build_findings_sections(findings_by_category, accent_color)
        quick_wins_section = PDFGenerator._build_quick_wins_section(quick_wins, accent_color)
        appendix = PDFGenerator._build_appendix(scan, redirect_chain)
        
        # Combine all sections
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                {PDFGenerator._get_css(primary_color, accent_color, brand_name)}
            </style>
        </head>
        <body>
            {cover_page}
            {toc_page}
            {executive_summary}
            {score_breakdown}
            {findings_sections}
            {quick_wins_section}
            {appendix}
        </body>
        </html>
        """
        return html
    
    @staticmethod
    def _get_css(primary_color: str, accent_color: str, brand_name: str) -> str:
        """Get CSS styles for PDF"""
        return f"""
        @page {{
            size: A4;
            margin: 2.5cm 2cm 3cm 2cm;
            
            @top-center {{
                content: "";
            }}
            
            @bottom-left {{
                content: "Generated by {brand_name}";
                font-size: 9pt;
                color: #64748b;
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            }}
            
            @bottom-right {{
                content: "Page " counter(page) " of " counter(pages);
                font-size: 9pt;
                color: #64748b;
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            }}
        }}
        
        @page:first {{
            @bottom-left {{
                content: "";
            }}
            @bottom-right {{
                content: "";
            }}
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            color: #0f172a;
            line-height: 1.7;
            font-size: 11pt;
        }}
        
        h1 {{
            font-size: 32pt;
            font-weight: 700;
            color: #0f172a;
            margin: 0 0 16pt 0;
            line-height: 1.2;
            letter-spacing: -0.5pt;
        }}
        
        h2 {{
            font-size: 24pt;
            font-weight: 600;
            color: #0f172a;
            margin: 40pt 0 20pt 0;
            padding-bottom: 12pt;
            border-bottom: 2px solid #e2e8f0;
            page-break-after: avoid;
        }}
        
        h3 {{
            font-size: 18pt;
            font-weight: 600;
            color: #0f172a;
            margin: 32pt 0 16pt 0;
            page-break-after: avoid;
        }}
        
        h4 {{
            font-size: 14pt;
            font-weight: 600;
            color: #0f172a;
            margin: 24pt 0 12pt 0;
            page-break-after: avoid;
        }}
        
        p {{
            margin: 0 0 12pt 0;
            color: #475569;
            font-size: 11pt;
            line-height: 1.7;
        }}
        
        .text-muted {{
            color: #64748b;
            font-size: 10pt;
        }}
        
        .text-small {{
            font-size: 9pt;
            color: #64748b;
        }}
        
        .cover-page {{
            page-break-after: always;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }}
        
        .cover-header {{
            border-top: 4px solid {primary_color};
            padding-top: 24pt;
            margin-bottom: 60pt;
        }}
        
        .cover-logo {{
            max-height: 60pt;
            margin-bottom: 20pt;
        }}
        
        .cover-title {{
            font-size: 36pt;
            font-weight: 700;
            color: #0f172a;
            margin: 0 0 8pt 0;
            line-height: 1.1;
        }}
        
        .cover-subtitle {{
            font-size: 14pt;
            color: #64748b;
            margin: 0 0 40pt 0;
        }}
        
        .cover-hero {{
            background: linear-gradient(135deg, {primary_color}15 0%, {accent_color}15 100%);
            border-left: 6px solid {accent_color};
            padding: 40pt;
            margin: 60pt 0;
            border-radius: 8pt;
        }}
        
        .cover-score {{
            font-size: 72pt;
            font-weight: 700;
            color: {accent_color};
            margin: 0;
            line-height: 1;
        }}
        
        .cover-risk {{
            display: inline-block;
            padding: 8pt 20pt;
            background: {accent_color};
            color: white;
            border-radius: 6pt;
            font-size: 14pt;
            font-weight: 600;
            text-transform: uppercase;
            margin-top: 16pt;
        }}
        
        .cover-meta {{
            margin-top: 60pt;
        }}
        
        .cover-meta-row {{
            margin-bottom: 12pt;
            font-size: 11pt;
        }}
        
        .cover-meta-label {{
            color: #64748b;
            display: inline-block;
            width: 140pt;
        }}
        
        .cover-meta-value {{
            color: #0f172a;
            font-weight: 500;
        }}
        
        .cover-disclaimer {{
            margin-top: 40pt;
            padding-top: 20pt;
            border-top: 1px solid #e2e8f0;
            font-size: 9pt;
            color: #94a3b8;
            text-align: center;
        }}
        
        .toc-page {{
            page-break-after: always;
        }}
        
        .toc-item {{
            margin-bottom: 12pt;
            padding: 8pt 0;
            border-bottom: 1px dotted #e2e8f0;
        }}
        
        .toc-item-title {{
            font-size: 13pt;
            font-weight: 600;
            color: #0f172a;
            margin: 0;
        }}
        
        .toc-item-desc {{
            font-size: 10pt;
            color: #64748b;
            margin: 4pt 0 0 0;
        }}
        
        .section {{
            page-break-inside: avoid;
        }}
        
        .finding-block {{
            page-break-inside: avoid;
            margin-bottom: 24pt;
            padding: 20pt;
            background: #f8fafc;
            border-left: 4px solid {accent_color};
            border-radius: 6pt;
        }}
        
        .finding-header {{
            display: flex;
            align-items: flex-start;
            gap: 12pt;
            margin-bottom: 12pt;
        }}
        
        .finding-severity {{
            display: inline-block;
            padding: 4pt 12pt;
            border-radius: 4pt;
            font-size: 9pt;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5pt;
            white-space: nowrap;
        }}
        
        .severity-critical {{
            background: #fee2e2;
            color: #991b1b;
        }}
        
        .severity-high {{
            background: #fef2f2;
            color: #dc2626;
        }}
        
        .severity-medium {{
            background: #fef3c7;
            color: #d97706;
        }}
        
        .severity-low {{
            background: #d1fae5;
            color: #065f46;
        }}
        
        .severity-info {{
            background: #e0e7ff;
            color: #3730a3;
        }}
        
        .finding-title {{
            font-size: 14pt;
            font-weight: 600;
            color: #0f172a;
            margin: 0 0 8pt 0;
            flex: 1;
        }}
        
        .finding-impact {{
            font-size: 11pt;
            color: #475569;
            margin: 0 0 12pt 0;
            font-style: italic;
        }}
        
        .finding-recommendation {{
            margin-top: 12pt;
            padding-top: 12pt;
            border-top: 1px solid #e2e8f0;
        }}
        
        .finding-recommendation-title {{
            font-size: 11pt;
            font-weight: 600;
            color: #0f172a;
            margin: 0 0 8pt 0;
        }}
        
        .finding-recommendation-text {{
            font-size: 11pt;
            color: #475569;
            margin: 0;
        }}
        
        .finding-effort {{
            display: inline-block;
            margin-top: 8pt;
            padding: 4pt 10pt;
            background: #f1f5f9;
            border-radius: 4pt;
            font-size: 9pt;
            color: #475569;
        }}
        
        .severity-breakdown {{
            display: grid;
            grid-template-columns: repeat(5, 1fr);
            gap: 12pt;
            margin: 24pt 0;
        }}
        
        .severity-stat {{
            text-align: center;
            padding: 16pt;
            background: #f8fafc;
            border-radius: 6pt;
        }}
        
        .severity-stat-count {{
            font-size: 24pt;
            font-weight: 700;
            color: #0f172a;
            margin: 0;
        }}
        
        .severity-stat-label {{
            font-size: 9pt;
            color: #64748b;
            text-transform: uppercase;
            margin-top: 4pt;
        }}
        
        .quick-win-item {{
            margin-bottom: 20pt;
            padding: 16pt;
            background: #f0fdf4;
            border-left: 4px solid {accent_color};
            border-radius: 6pt;
        }}
        
        .quick-win-checkbox {{
            display: inline-block;
            width: 16pt;
            height: 16pt;
            border: 2px solid {accent_color};
            border-radius: 3pt;
            margin-right: 12pt;
            vertical-align: middle;
        }}
        
        .quick-win-title {{
            font-size: 13pt;
            font-weight: 600;
            color: #0f172a;
            margin: 0 0 8pt 0;
        }}
        
        .quick-win-desc {{
            font-size: 11pt;
            color: #475569;
            margin: 0;
        }}
        
        .appendix-table {{
            width: 100%;
            border-collapse: collapse;
            margin: 16pt 0;
        }}
        
        .appendix-table td {{
            padding: 10pt;
            border-bottom: 1px solid #e2e8f0;
            font-size: 10pt;
        }}
        
        .appendix-table td:first-child {{
            color: #64748b;
            font-weight: 600;
            width: 180pt;
        }}
        
        .appendix-table td:last-child {{
            color: #0f172a;
            word-break: break-all;
        }}
        
        .url-wrap {{
            word-break: break-all;
            word-wrap: break-word;
            max-width: 100%;
        }}
        """
    
    @staticmethod
    def _get_logo_html(brand: Optional[BrandProfile]) -> str:
        """Get logo HTML for brand"""
        if not brand or not brand.logo_base64:
            return ""
        
        # Handle base64 logo
        logo_data = brand.logo_base64
        if not logo_data.startswith('data:'):
            logo_data = f"data:image/png;base64,{logo_data}"
        
        return f'<img src="{logo_data}" class="cover-logo" alt="{brand.name}" />'
    
    @staticmethod
    def _group_findings(findings: List[Finding]) -> Dict[str, List[Finding]]:
        """Group findings by category and sort by severity"""
        grouped = defaultdict(list)
        for finding in findings:
            grouped[finding.category.value].append(finding)
        
        # Sort each category by severity
        severity_order = {
            FindingSeverity.CRITICAL: 0,
            FindingSeverity.HIGH: 1,
            FindingSeverity.MEDIUM: 2,
            FindingSeverity.LOW: 3,
            FindingSeverity.INFO: 4
        }
        
        for category in grouped:
            grouped[category].sort(key=lambda f: severity_order.get(f.severity, 99))
        
        return dict(grouped)
    
    @staticmethod
    def _get_severity_counts(findings: List[Finding]) -> Dict[str, int]:
        """Get count of findings by severity"""
        counts = defaultdict(int)
        for finding in findings:
            counts[finding.severity.value] += 1
        return dict(counts)
    
    @staticmethod
    def _get_quick_wins(findings: List[Finding]) -> List[Finding]:
        """Get top 3 quick wins (medium/high severity with effort <= 60 min)"""
        quick_wins = []
        
        for finding in findings:
            effort = PDFGenerator._estimate_effort(finding)
            if effort and effort <= 60:
                if finding.severity in [FindingSeverity.MEDIUM, FindingSeverity.HIGH]:
                    quick_wins.append(finding)
        
        # If not enough, add low/info
        if len(quick_wins) < 3:
            for finding in findings:
                if finding not in quick_wins:
                    effort = PDFGenerator._estimate_effort(finding)
                    if effort and effort <= 60:
                        quick_wins.append(finding)
                        if len(quick_wins) >= 3:
                            break
        
        return quick_wins[:3]
    
    @staticmethod
    def _estimate_effort(finding: Finding) -> Optional[int]:
        """Estimate effort in minutes based on finding type"""
        title_lower = finding.title.lower()
        category = finding.category.value
        severity = finding.severity.value
        
        # Security headers
        if category == "security" and any(h in title_lower for h in ["hsts", "csp", "x-frame", "x-content-type"]):
            if severity in ["critical", "high"]:
                return 15
            return 30
        
        # Cookie/GDPR
        if category == "gdpr" or "cookie" in title_lower:
            return 120
        
        # Version disclosure
        if "version" in title_lower or "server" in title_lower:
            return 30
        
        # Robots
        if "robot" in title_lower:
            return 10
        
        # Default estimates
        if severity == "critical":
            return 45
        elif severity == "high":
            return 60
        elif severity == "medium":
            return 30
        elif severity == "low":
            return 15
        else:
            return 10
    
    @staticmethod
    def _format_effort(minutes: Optional[int]) -> str:
        """Format effort estimate as human-readable string"""
        if not minutes:
            return "~30 min"
        
        if minutes < 60:
            return f"~{minutes} min"
        elif minutes == 60:
            return "~1 hour"
        else:
            hours = minutes // 60
            mins = minutes % 60
            if mins == 0:
                return f"~{hours} hour{'s' if hours > 1 else ''}"
            return f"~{hours}h {mins}m"
    
    @staticmethod
    def _parse_redirect_chain(redirect_chain) -> List[str]:
        """Parse redirect chain from JSON string or list"""
        if not redirect_chain:
            return []
        
        try:
            import json
            if isinstance(redirect_chain, str):
                return json.loads(redirect_chain)
            return redirect_chain if isinstance(redirect_chain, list) else []
        except:
            return []
    
    @staticmethod
    def _build_cover_page(scan: Scan, brand: Optional[BrandProfile], logo_html: str,
                         primary_color: str, accent_color: str, brand_name: str, prepared_for: str) -> str:
        """Build cover page HTML"""
        score = scan.overall_score or 0
        risk_level = scan.risk_level.value if scan.risk_level else "info"
        risk_display = risk_level.replace("_", " ").title()
        
        scan_date = scan.created_at.strftime('%B %d, %Y') if scan.created_at else datetime.now().strftime('%B %d, %Y')
        scan_time = scan.created_at.strftime('%I:%M %p') if scan.created_at else datetime.now().strftime('%I:%M %p')
        
        return f"""
        <div class="cover-page">
            <div class="cover-header">
                {logo_html if logo_html else f'<h2 style="color: {primary_color}; margin: 0 0 20pt 0;">{brand_name}</h2>'}
                <h1 class="cover-title">Website Security & Compliance Report</h1>
                <p class="cover-subtitle">Prepared for: <strong>{prepared_for}</strong></p>
                <p class="cover-subtitle">Prepared by: <strong>{brand_name}</strong></p>
            </div>
            
            <div class="cover-hero">
                <p class="cover-score">{int(score)}</p>
                <span class="cover-risk">{risk_display} Risk</span>
            </div>
            
            <div class="cover-meta">
                <div class="cover-meta-row">
                    <span class="cover-meta-label">Scan Date:</span>
                    <span class="cover-meta-value">{scan_date} at {scan_time}</span>
                </div>
                <div class="cover-meta-row">
                    <span class="cover-meta-label">URL Scanned:</span>
                    <span class="cover-meta-value url-wrap">{scan.url}</span>
                </div>
                {f'<div class="cover-meta-row"><span class="cover-meta-label">Final URL:</span><span class="cover-meta-value url-wrap">{scan.final_url}</span></div>' if scan.final_url and scan.final_url != scan.url else ''}
            </div>
            
            <div class="cover-disclaimer">
                Non-invasive, read-only checks. Not a penetration test.
            </div>
        </div>
        """
    
    @staticmethod
    def _build_toc_page() -> str:
        """Build table of contents page"""
        return """
        <div class="toc-page section">
            <h2>Table of Contents</h2>
            
            <div class="toc-item">
                <p class="toc-item-title">1. Executive Summary</p>
                <p class="toc-item-desc">Overview of scan results and key metrics</p>
            </div>
            
            <div class="toc-item">
                <p class="toc-item-title">2. Score & Severity Breakdown</p>
                <p class="toc-item-desc">Detailed scoring analysis and risk assessment</p>
            </div>
            
            <div class="toc-item">
                <p class="toc-item-title">3. Findings</p>
                <p class="toc-item-desc">Detailed findings organized by category</p>
            </div>
            
            <div class="toc-item">
                <p class="toc-item-title">4. Quick Wins</p>
                <p class="toc-item-desc">High-impact improvements you can make in under 60 minutes</p>
            </div>
            
            <div class="toc-item">
                <p class="toc-item-title">5. Appendix</p>
                <p class="toc-item-desc">Technical details and metadata</p>
            </div>
        </div>
        """
    
    @staticmethod
    def _build_executive_summary(scan: Scan, severity_counts: Dict[str, int]) -> str:
        """Build executive summary section"""
        total_findings = len(scan.findings)
        score = scan.overall_score or 0
        risk_level = scan.risk_level.value if scan.risk_level else "info"
        
        critical_count = severity_counts.get("critical", 0)
        high_count = severity_counts.get("high", 0)
        
        summary_text = f"""
        This security and compliance scan of <strong>{scan.url}</strong> identified <strong>{total_findings} findings</strong> 
        across security, GDPR, and SEO categories. The overall security score is <strong>{int(score)}/100</strong>, 
        indicating a <strong>{risk_level.replace('_', ' ').title()} Risk</strong> level.
        """
        
        if critical_count > 0 or high_count > 0:
            summary_text += f"""
            <strong>{critical_count + high_count} critical or high-severity issues</strong> require immediate attention 
            to improve security posture and compliance.
            """
        else:
            summary_text += """
            No critical or high-severity issues were detected. Focus on addressing medium and low-severity findings 
            to further improve the security score.
            """
        
        return f"""
        <div class="section">
            <h2>1. Executive Summary</h2>
            <p>{summary_text}</p>
            <p class="text-muted">
                This report provides actionable recommendations to improve your website's security, GDPR compliance, 
                and SEO performance. Each finding includes specific remediation steps and estimated effort.
            </p>
        </div>
        """
    
    @staticmethod
    def _build_score_breakdown(scan: Scan, severity_counts: Dict[str, int], accent_color: str) -> str:
        """Build score and severity breakdown section"""
        score = scan.overall_score or 0
        risk_level = scan.risk_level.value if scan.risk_level else "info"
        risk_display = risk_level.replace("_", " ").title()
        
        severity_html = ""
        for severity in ["critical", "high", "medium", "low", "info"]:
            count = severity_counts.get(severity, 0)
            severity_html += f"""
            <div class="severity-stat">
                <p class="severity-stat-count">{count}</p>
                <p class="severity-stat-label">{severity.title()}</p>
            </div>
            """
        
        return f"""
        <div class="section">
            <h2>2. Score & Severity Breakdown</h2>
            
            <div style="background: #f8fafc; padding: 24pt; border-radius: 8pt; margin: 24pt 0;">
                <p style="margin: 0 0 12pt 0; font-size: 13pt; color: #64748b;">Overall Security Score</p>
                <p style="font-size: 48pt; font-weight: 700; color: {accent_color}; margin: 0 0 12pt 0;">{int(score)}/100</p>
                <span style="display: inline-block; padding: 6pt 16pt; background: {accent_color}; color: white; border-radius: 6pt; font-size: 12pt; font-weight: 600; text-transform: uppercase;">
                    {risk_display} Risk
                </span>
            </div>
            
            <h3>Findings by Severity</h3>
            <div class="severity-breakdown">
                {severity_html}
            </div>
        </div>
        """
    
    @staticmethod
    def _build_findings_sections(findings_by_category: Dict[str, List[Finding]], accent_color: str) -> str:
        """Build findings sections grouped by category"""
        category_names = {
            "security": "Security",
            "gdpr": "GDPR & Privacy",
            "seo": "SEO",
            "other": "Other"
        }
        
        sections = []
        section_num = 3
        
        for category_key in ["security", "gdpr", "seo", "other"]:
            if category_key not in findings_by_category:
                continue
            
            findings = findings_by_category[category_key]
            category_name = category_names.get(category_key, category_key.title())
            
            findings_html = ""
            for finding in findings:
                effort_min = PDFGenerator._estimate_effort(finding)
                effort_str = PDFGenerator._format_effort(effort_min)
                severity_class = f"severity-{finding.severity.value}"
                
                # Extract impact from description (first sentence)
                impact = finding.description.split('.')[0] if finding.description else finding.description
                
                findings_html += f"""
                <div class="finding-block">
                    <div class="finding-header">
                        <span class="finding-severity {severity_class}">{finding.severity.value.title()}</span>
                        <h4 class="finding-title">{finding.title}</h4>
                    </div>
                    <p class="finding-impact"><strong>Impact:</strong> {impact}</p>
                    {f'<div class="finding-recommendation"><p class="finding-recommendation-title">Recommendation:</p><p class="finding-recommendation-text">{finding.recommendation}</p></div>' if finding.recommendation else ''}
                    <span class="finding-effort">Estimated effort: {effort_str}</span>
                </div>
                """
            
            sections.append(f"""
            <div class="section">
                <h2>{section_num}. {category_name} Findings</h2>
                {findings_html}
            </div>
            """)
            section_num += 1
        
        return "\n".join(sections)
    
    @staticmethod
    def _build_quick_wins_section(quick_wins: List[Finding], accent_color: str) -> str:
        """Build quick wins section"""
        if not quick_wins:
            return """
            <div class="section">
                <h2>4. Quick Wins</h2>
                <p class="text-muted">No quick wins identified. Focus on addressing the findings in the previous sections.</p>
            </div>
            """
        
        items_html = ""
        for win in quick_wins:
            effort_min = PDFGenerator._estimate_effort(win)
            effort_str = PDFGenerator._format_effort(effort_min)
            items_html += f"""
            <div class="quick-win-item">
                <span class="quick-win-checkbox"></span>
                <div style="display: inline-block; width: calc(100% - 32pt); vertical-align: top;">
                    <p class="quick-win-title">{win.title}</p>
                    <p class="quick-win-desc">{win.description}</p>
                    <p class="text-small" style="margin-top: 8pt;">Estimated effort: {effort_str}</p>
                </div>
            </div>
            """
        
        return f"""
        <div class="section">
            <h2>4. Quick Wins (Under 60 Minutes)</h2>
            <p class="text-muted">
                These high-impact improvements can be implemented quickly to improve your security score.
            </p>
            {items_html}
        </div>
        """
    
    @staticmethod
    def _build_appendix(scan: Scan, redirect_chain: List[str]) -> str:
        """Build appendix with technical details"""
        redirect_html = ""
        if redirect_chain:
            redirect_html = "<ol style='margin: 0; padding-left: 20pt;'>"
            for url in redirect_chain:
                redirect_html += f"<li style='margin-bottom: 4pt; word-break: break-all;'>{url}</li>"
            redirect_html += "</ol>"
        else:
            redirect_html = "<p class='text-muted'>No redirects detected.</p>"
        
        # Headers checked (common security headers)
        headers_checked = [
            "Strict-Transport-Security (HSTS)",
            "Content-Security-Policy (CSP)",
            "X-Frame-Options",
            "X-Content-Type-Options",
            "Referrer-Policy",
            "Permissions-Policy"
        ]
        
        headers_html = "<ul style='margin: 0; padding-left: 20pt;'>"
        for header in headers_checked:
            headers_html += f"<li style='margin-bottom: 4pt;'>{header}</li>"
        headers_html += "</ul>"
        
        scan_timestamp = scan.created_at.strftime('%Y-%m-%d %H:%M:%S UTC') if scan.created_at else "N/A"
        
        return f"""
        <div class="section">
            <h2>5. Appendix: Technical Details</h2>
            
            <table class="appendix-table">
                <tr>
                    <td>Normalized URL</td>
                    <td class="url-wrap">{scan.normalized_url or scan.url or 'N/A'}</td>
                </tr>
                <tr>
                    <td>Final URL</td>
                    <td class="url-wrap">{scan.final_url or scan.url or 'N/A'}</td>
                </tr>
                <tr>
                    <td>HTTP Status Code</td>
                    <td>{scan.response_status or 'N/A'}</td>
                </tr>
                <tr>
                    <td>Scan Timestamp</td>
                    <td>{scan_timestamp}</td>
                </tr>
            </table>
            
            <h3>Redirect Chain</h3>
            {redirect_html}
            
            <h3>Security Headers Checked</h3>
            {headers_html}
        </div>
        """
